# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import compute_pb2 as compute__pb2


class ComputeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/compute.Compute/SayHello',
                request_serializer=compute__pb2.HelloRequest.SerializeToString,
                response_deserializer=compute__pb2.HelloReply.FromString,
                )
        self.SayHello2 = channel.unary_unary(
                '/compute.Compute/SayHello2',
                request_serializer=compute__pb2.HelloRequest.SerializeToString,
                response_deserializer=compute__pb2.HelloReply.FromString,
                )
        self.GetLen = channel.unary_unary(
                '/compute.Compute/GetLen',
                request_serializer=compute__pb2.HelloRequest.SerializeToString,
                response_deserializer=compute__pb2.HelloReplyInt.FromString,
                )


class ComputeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """我们rpc服务的名字
        后面
        服务端 会用到 <ComputeServicer>
        客户端 会用到 <ComputeStub>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello2(self, request, context):
        """SayHello 调用的方法
        HelloRequest 客户端输入的消息（对象）
        returns 服务端
        HelloReply 服务端 返回的消息（对象）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=compute__pb2.HelloRequest.FromString,
                    response_serializer=compute__pb2.HelloReply.SerializeToString,
            ),
            'SayHello2': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello2,
                    request_deserializer=compute__pb2.HelloRequest.FromString,
                    response_serializer=compute__pb2.HelloReply.SerializeToString,
            ),
            'GetLen': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLen,
                    request_deserializer=compute__pb2.HelloRequest.FromString,
                    response_serializer=compute__pb2.HelloReplyInt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'compute.Compute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Compute(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compute.Compute/SayHello',
            compute__pb2.HelloRequest.SerializeToString,
            compute__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compute.Compute/SayHello2',
            compute__pb2.HelloRequest.SerializeToString,
            compute__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/compute.Compute/GetLen',
            compute__pb2.HelloRequest.SerializeToString,
            compute__pb2.HelloReplyInt.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
